### PR TITLE
chore: type hinting

### PR DESCRIPTION
**Pull request by holyachon**
due to https://github.com/Fatal1ty/aiofcm/pull/15#discussion_r1133243587

- changed old type hinting style to new one.
- add type hintings into missing part.

### CODE REVIEW

**Comment by holyachon** [comment]
I also want to add CI like [here](https://github.com/Fatal1ty/aioapns/blob/master/.github/workflows/ci.yml). But it will make big diffs, so I will do it after #15, #16 merged.

**Comment by Fatal1ty** [comment]
There're some conflicts with the new `max_connection_attempts` argument you added but everything else is good!

**Comment by holyachon** [comment]
> There're some conflicts with the new `max_connection_attempts` argument you added but everything else is good!

@Fatal1ty Could you please check it again? I have resolved the conflict now.

**Comment by Fatal1ty** [comment]
> @Fatal1ty Could you please check it again? I have resolved the conflict now.

Looks good!

> I also want to add CI like [here](https://github.com/Fatal1ty/aioapns/blob/master/.github/workflows/ci.yml). But it will make big diffs, so I will do it after #15, #16 merged.

Will be ready to make a new release after that 🙏

**Pull request merged**
